### ISSUE TITLE
Tutoring Page

### ISSUE THREAD

**Issue by vyas0189** [CougarCS/CougarCS-Client#22]
Figma Link: https://www.figma.com/file/EWJza5GkVvYUyyaaHF19ZW/Cougar-CS?node-id=74%3A69

![image](https://user-images.githubusercontent.com/17396599/94489688-8a392100-01aa-11eb-9fc8-3ef137dec096.png)

- Become a tutor link has a mailto link to tutoring@cougarcs.com with subject: CougarCS Tutor Application

**Comment by Haidvu** [comment]
I would like to work on this. Has anyone else started?

**Comment by vyas0189** [comment]
You can start working on this. @Haidvu

**Comment by rohittaneja0** [comment]
@shubhsheth @vyas0189 I want to work on this issue, and can you confirm if you want the specs to remain the same?
