### ISSUE TITLE
Registration Page Fixes

### ISSUE THREAD

**Issue by crudemandarin** [CougarCS/CougarCS-Client#228]
Changes in regards to the integration of CougarCS-Cloud in CougarCS-Backend. Let's introduce cool and useful features with the power of our API and member database!

**Fixes**
- Change "Classification" field to "Shirt Size". Acceptable inputs: S, M, L, XL, XXL
- Replace CougarCS-Backend payment call "classification" variable to shirt size.

**Comment by crudemandarin** [comment]
@shubhsheth I remember you mentioned something about the shirt size field change, have you already made progress on this fix? I can focus on the new widget!

**Comment by shubhsheth** [comment]
@crudemandarin here's the PR for that https://github.com/CougarCS/CougarCS-Client/pull/223
