### ISSUE TITLE
Registration Page Enhancement: Prevent Purchase if Already Member

### ISSUE THREAD

**Issue by crudemandarin** [CougarCS/CougarCS-Client#233]
Before invoking /payment of CougarCS-Backend, make a call to CougarCS-Cloud /contact/status to check if a user is already a member. If membership status is true, end the transaction and inform the user of their status and end date.

**Comment by nguyenhung15913** [comment]
Hi, I would like to contribute to this project. If you accept this request , I have some questions related to the issue:
- Do users have to register first to buy the member ship?
- What is UHID in the register form? I tried to register but I the button show loading... and it seemed like I enter wrong UHID so nothing happened after.
