### ISSUE TITLE
Mailing list sign up

### ISSUE THREAD

**Issue by shubhsheth** [CougarCS/CougarCS-Client#244]
Create a sign up form in the footer to allow anyone to receive CougarCS updates via newsletter 

@shubhsheth to create a figma design for this

**Comment by crudemandarin** [comment]
There is interest among students to subscribe to our newsletter without being a member. We should expose functionality on our website to enable users to subscribe to our newsletter automatically without needing to contact us.

See the image example below from one of our peer organizations, UH SWE.

![image](https://user-images.githubusercontent.com/29151058/131374531-1d0d4d27-4af5-4830-b177-8ec782a6bd2b.png)

**Comment by mayankdp** [comment]
Hii.  I am interested in this issue. Can I work on it?

**Comment by KevFlo** [comment]
Feel free to work on it, if you need any assistance you can ping me or @shubhsheth

**Comment by mayankdp** [comment]
Awesome. Thank You very much.

**Comment by mayankdp** [comment]
Hii @shubhsheth and @KevFlo 
I have created a button (see the attached image) but I am confused with the next part. I have looked at the UH SWE's website and when I click the button to sign up, it takes me to a google form to fill out First name, Last name, and email. So, Are we doing the same thing as UH SWE?

<img width="1436" alt="Screen Shot 2022-02-19 at 4 59 38 PM" src="https://user-images.githubusercontent.com/45217514/154820667-c1ea86b3-c86e-4c77-8484-2fc8253ff73b.png">

**Comment by shubhsheth** [comment]
@mayankdp 
The newsletter section would need to be a form with following fields (First Name, Last Name, Email)
Next to those fields there would be a button that says 'Sign Up', when the user click on that button the fields would be verified for valid input. Then it'll be sent to the backend for it to be logged.
Once the backend confirms data has been received, we'll show a success pop up on the page. For any error there would be an error pop up.

References:
- There is a contact form already built that takes input and sends data to the backend: https://github.com/CougarCS/CougarCS-Client/blob/master/src/components/ContactForm/ContactForm.js
- The success and error popups are already created you can reuse those components like this: https://github.com/CougarCS/CougarCS-Client/blob/master/src/components/Payment/Payment.js#L108-L117

Additionally, there needs to be a backend issue created to build that endpoint. I can create that assign it to you if you'd like to work on that.

**Comment by shubhsheth** [comment]
Design wise there are 2 options:
![image](https://user-images.githubusercontent.com/17396599/154858005-c456d6d7-9df2-4050-889a-d9e2dc289fb9.png)
This is a simple form that can go above footer on all pages

![image](https://user-images.githubusercontent.com/17396599/154858057-9a728c07-ad60-4c61-88b0-52e3fb0536dd.png)
This second version is where we'd update the footer to something like this. Once the user fills the email we show the popup to ask for first and last name which will then be sent to backend for processing

Here's the figma link for accurate dimensions: https://www.figma.com/file/EWJza5GkVvYUyyaaHF19ZW/CougarCS?node-id=74%3A2

**Comment by mayankdp** [comment]
> @mayankdp The newsletter section would need to be a form with following fields (First Name, Last Name, Email) Next to those fields there would be a button that says 'Sign Up', when the user click on that button the fields would be verified for valid input. Then it'll be sent to the backend for it to be logged. Once the backend confirms data has been received, we'll show a success pop up on the page. For any error there would be an error pop up.
> 
> References:
> 
> * There is a contact form already built that takes input and sends data to the backend: https://github.com/CougarCS/CougarCS-Client/blob/master/src/components/ContactForm/ContactForm.js
> * The success and error popups are already created you can reuse those components like this: https://github.com/CougarCS/CougarCS-Client/blob/master/src/components/Payment/Payment.js#L108-L117
> 
> Additionally, there needs to be a backend issue created to build that endpoint. I can create that assign it to you if you'd like to work on that.

Hii @shubhsheth 
I have used the first design. Please create a backend issue and assign it to me so I can work on it.
Also, can you assign this issue to me?
Below is the design I have created.
<img width="720" alt="Screen Shot 2022-02-20 at 4 26 57 PM" src="https://user-images.githubusercontent.com/45217514/154864983-543432f7-3870-46ce-84f1-fa4323a4032a.png">

**Comment by shubhsheth** [comment]
The colors, spacing and scale are a bit of a mismatch from the figma design, if you click on the link above, you'll be able to capture all the dimensions, font sizing and colors for this section

**Comment by KevFlo** [comment]
@mayankdp please accept invitation to BE so we can assign the issue to you

**Comment by mayankdp** [comment]
Hii @shubhsheth 
I was able to change some spacing and scales from the Figma design. There is still space between the footer and newsletter signup which I was not able to figure out yet. I will work on that.

Hii @KevFlo 
I have accepted the invitation. I will need to help with setting up BE.

**Comment by mayankdp** [comment]
Hello. I am done with this frontend side. I have commented on the code that sends data to the backend. Please test it and give me feedback so if anything needs to change, I can do it.
Here is a screenshot of it:
<img width="1440" alt="Screen Shot 2022-03-21 at 11 10 02 PM" src="https://user-images.githubusercontent.com/45217514/159400206-975e90b1-0a24-40cc-8be8-fa93332e2de9.png">
.

**Comment by mayankdp** [comment]
Hii So, I have been getting this error that the api/newsLetterEmails not found. How can I create that API path to store the data?

<img width="437" alt="Screen Shot 2022-03-22 at 12 47 12 AM" src="https://user-images.githubusercontent.com/45217514/159412397-d6bbb384-c056-4c6c-8151-24fec9821d8f.png">

I have been working on the backend and I have done the backend for this newsletteremails similar to Contact Form.

**Comment by shubhsheth** [comment]
@mayankdp Can you do a quick deployment of your repo on netlify so we can verify your changes? (make sure it's the correct branch).

For your API path issue, it looks like it may have something to do with your .env file. Can you check:
1. Other routes are working when triggered from frontend
2. Your route returns correct information when you test a request from postman

**Comment by mayankdp** [comment]
Hii @shubhsheth 
I quite not understand what do you mean by deploying my repo on netlify. Is it like do I need to create a pull request? I have never done this netlify so if you can help me on this, that would be appreciated.

For the API path, I have done similar to contact form. I will still try to figure out and do the checks that you have mentioned.

**Comment by shubhsheth** [comment]
@mayankdp - I looked at your code, it seems like either you don't have a `.env` file for your frontend or it's not setup correctly. Can you create one following this: https://github.com/CougarCS/CougarCS-Client#optional-setup. (Don't worry about getting the stripe and recaptcha key, you only need `REACT_APP_API_URL` to be correct). The `REACT_APP_API_URL` would be set to the url you get when you run `yarn server` for your backend

**Comment by shubhsheth** [comment]
@mayankdp  That's correct we would need to create an endpoint for this. It would be `/newsletter` given the other endpoints follow this naming scheme.

For resources I would recommend looking up tutorials for Node and Express on youtube. We're also using jest for testing the endpoints so you can learn that as well.

**Comment by mayankdp** [comment]
Ok. I have changed it to `/newsletter`.

@shubhsheth Hii.
This issue is done. right? The reason I am asking is because I have to submit a summary to my professor that this issue has been completed by end of this week. So, I would like to create pull request for approval.

**Comment by shubhsheth** [comment]
@mayankdp I think overall the client changes look good, I can comment further on tiny fixes (if needed) when you create the PR.

But since this feature is backend dependent, the endpoint would need to be merged into master first. I made some comments on how to handle PR approval for your project in backend issue. We can also do the same here, create a PR for 'feature/newsletter' branch and then you can continue working on it after submitting your summary

**Comment by mayankdp** [comment]
@shubhsheth Thank you very much for understanding. I will go ahead and create PR for approval for both FrontEnd and Backend.
Sorry for replying late, since the finals are in a week, I have been very busy with other assignments.

**Comment by mayankdp** [comment]
@shubhsheth Can you create a 'feature/newsletter' branch on main repo? I could not find this branch on the main repo. And I have been working from the forked repo. And also same for backend, please create 'feature/newsletter' branch.

**Comment by shubhsheth** [comment]
@mayankdp Added a branch for both Client and Backend repos

**Comment by mayankdp** [comment]
@shubhsheth Thank you. I have created pull requests for both the frontend and backend. When you have time, please approve the code.

**Comment by shubhsheth** [comment]
@mayankdp Both PRs are failing tests, please review and update them

**Comment by mayankdp** [comment]
Hii @shubhsheth 
I have resolved the conflict files for both PRs.

Frontend: 
-  security/snyk (cougarcs) — 1 test has failed

Backend: 
- Install, Test, Build / lint (pull_request) Failing after 1m — lint
- Install, Test, Build / sonar-coverage (pull_request) Failing after 23s

These security tests have failed. Please help. How can I resolve this?

**Comment by shubhsheth** [comment]
@mayankdp There is instructions for this in readme files of the repositories. Please review them.

For snyk failure, I see that you have a new package `dotenv` which is not being used anywhere. I would recommend removing this. 

@vyas0189  Could you see if there is anything else that's causing snyk check to fail? - I'm not able to access this.

**Comment by vyas0189** [comment]
> 

Hi @mayankdp, you Snyk will fail because of the CI didn't pass (https://github.com/CougarCS/CougarCS-Client/runs/6168934093?check_suite_focus=true). Please follow the README to setup the project correctly
