### ISSUE TITLE
[URGENT] Update CougarCS Discord Invite Link

### ISSUE THREAD

**Issue by crudemandarin** [CougarCS/CougarCS-Client#278]
Current invite link on front-end is dead, we need to replace this ASAP! Discord is our primary online platform.

New Discord Invite Link: https://discord.gg/wEagwaXS7F

**Comment by KevFlo** [comment]
which one is broken?
the one on the footer works? ill check the rest but id like to know which one

**Comment by KevFlo** [comment]
found it it was the contact us form

**Comment by KevFlo** [comment]
components/contactform.js is where the issue is. can you please change this real quick @mayssam73  i got a quiz in a bit

**Comment by crudemandarin** [comment]
can we also replace the discord link in the footer? It points to a weird channel

**Comment by crudemandarin** [comment]
Great work thank you team! @mayssam73
