### ISSUE TITLE
Host CougarCS Information Packet on CougarCS Website

### ISSUE THREAD

**Issue by crudemandarin** [CougarCS/CougarCS-Client#285]
[Information Packet](https://docs.google.com/document/d/19VczLYr3j1rrIl337YlBcWzCp8TBCKrHqhCJmQ6TGNs/edit)

This packet has been a critical part of our member onboard and communication strategy. It has proven immense value in nearly every interaction with students interested to learn about our club.

Rather than attach a PDF to every email and direct people to a Google Drive folder, let's host this on www.cougarcs.com/info (for example). When people go to this link, it loads the PDF file nice and easy.

This solves a few problems:
- We don't need to attach a PDF file to communications
- We can easily direct people to information
- The link is fixed. We can update the file freely and not worry about QR codes or whatever downstream

I achieve a similar effect on my personal website (nykolas.me) with my resume. It's just a PDF in the website public HTML folder and I directly link it.

**Comment by vyas0189** [comment]
Only a url should be there, I don't think there should be a link in the Navbar. That link link in the Navbar will defeat the purpose of a website: https://deploy-preview-286--practical-hodgkin-4543e2.netlify.app/info @LeftAutomated

**Comment by crudemandarin** [comment]
Wowwwwwwwwwwwwww what incredible turn-around 😂😂 Thank you @LeftAutomated for hopping right on this!!
