### ISSUE TITLE
Payment Component (Stripe)

### ISSUE THREAD

**Issue by vyas0189** [CougarCS/CougarCS-Client#35]
Online payment method, user can choose one semester or one-year payment.

![image](https://user-images.githubusercontent.com/25915724/66327157-f367ba80-e8ef-11e9-9b5e-8fa8653ead78.png)

User input should include Name, Classification, Email, Phone Number, PSID.

**Comment by shubhsheth** [comment]
@vyas0189  Can you assign this to me
