### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by ZacharyPage** [CougarCS/CougarCS-Client#40]
Ibrahim brought an idea to my attention during the MLH local-hack day event that we should implement a blog like concept to the website, so that we can promote events along with a brief summary of what happened.

**Comment by vyas0189** [comment]
Do you want to combine the Gallery page and blog together? @ZacharyPage

**Comment by ZacharyPage** [comment]
Yeah, that could work. I just need to visualize how the two would work together considering we haven't finalized a gallery design yet. We can iron out the details during the meeting tomorrow.

**Comment by vyas0189** [comment]
![Screen Shot 2019-10-22 at 11 10 15 AM](https://user-images.githubusercontent.com/25915724/67306537-c0f7b900-f4bc-11e9-9881-dc0fafd471cb.png)
@ZacharyPage

**Comment by shubhsheth** [comment]
@ZacharyPage @vyas0189 Added more features in Gallery and Blog Layout: https://www.figma.com/file/EWJza5GkVvYUyyaaHF19ZW/Cougar-CS?node-id=38%3A3 Comment on the layout if you have any suggestions

**Comment by vyas0189** [comment]
I like the layout and the design, we will get started on the backend so it's easier to store and get the posts

**Comment by KevFlo** [comment]
I want to convert this blog idea into more of a student/member promotion.
some of these things could be:
-they create something (app/robot/anything technical)
-non-web dev committee members create PR that we use or find/ fix bugs
-internship acceptance/full-time acceptance

let me know what you guys think @shubhsheth @vyas0189
