### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by vyas0189** [CougarCS/CougarCS-Client#41]
![Screen Shot 2019-10-31 at 1 33 30 PM](https://user-images.githubusercontent.com/25915724/67975935-12055c80-fbe3-11e9-99c8-56ccb7a3fe40.png)

**Comment by Haidvu** [comment]
I'll start working on this after my tests next week.

**Comment by vyas0189** [comment]
Contact Us Page is finished.
