### ISSUE TITLE
Fix navigation link color bug

### ISSUE THREAD

**Issue by bnleft** [CougarCS/CougarCS-Client#517]
There is a small bug with the navigation bar.

After clicking on any navigation link and then clicking the CougarCS logo (home page)
the previous navigation link text remains red

Fix this so the text becomes black when the logo is clicked.

Example:
`Gallery` should be black, not red
![image](https://user-images.githubusercontent.com/80173797/180943030-cb510b9b-6a92-4e75-8ccb-79f24c7a12bb.png)

**Comment by ndminhvn** [comment]
Do you think it is possible to add a `Nav.Link` to homepage inside the `Navbar.Brand` logo?
If so, when we click on the logo, it'll direct back to the homepage, and the previous navigation link will become inactive.

**Comment by LeftAutomated** [comment]
> Do you think it is possible to add a `Nav.Link` to homepage inside the `Navbar.Brand` logo? If so, when we click on the logo, it'll direct back to the homepage, and the previous navigation link will become inactive.

I don't think that is possible. Feel free to try though, appreciate you for taking this on :)

**Comment by ndminhvn** [comment]
How can I make a pull request, so then you can review it? Currently, I don't have permission to push anything.

**Comment by LeftAutomated** [comment]
> How can I make a pull request, so then you can review it? Currently, I don't have permission to push anything.

- Fork this repository
- Make local changes to the forked repository
- Create a pull request in your forked repository

**Comment by ChristopherOosthuizen** [comment]
I believe I have made a elegant solution to this problem
