### ISSUE TITLE
[ URGENT ] Fix Build Bug

### ISSUE THREAD

**Issue by LeftAutomated** [CougarCS/CougarCS-Client#520]
This issue blocks future changes from being pushed to production

Log:
https://app.netlify.com/sites/practical-hodgkin-4543e2/deploys/630d4a36a8e58a0008373776

**Comment by shubhsheth** [comment]
I've tried the following things and still getting the same error:
- upgrade stripe packages
- remove stripe component completely
- remove api requests that happen on page load (tutors, events)
- revert last few commits for package upgrades

@vyas0189  Any idea what could be going on here?

**Comment by LeftAutomated** [comment]
> I've tried the following things and still getting the same error:
> 
> * upgrade stripe packages
> * remove stripe component completely
> * remove api requests that happen on page load (tutors, events)
> * revert last few commits for package upgrades
> 
> @vyas0189 Any idea what could be going on here?

Thanks to @vyas0189, he helped me fix this bug by removing react snap script.
