### ISSUE TITLE
Add Twitter logo in Footer

### ISSUE THREAD

**Issue by bnleft** [CougarCS/CougarCS-Client#526]
Add a clickable Twitter logo in the Footer. When clicked, it should link to `https://twitter.com/uhcougarcs`

Steps:
- Find a transparent Twitter logo
- Resize the image to 30x30 (approximate)
- Convert the image to `.webp`
- Add the image to the right of the GitHub logo in the Footer

Note: Try to be consistent with code and naming

![image](https://user-images.githubusercontent.com/80173797/187990469-47a592dd-f822-432d-bcc5-021b7ae66682.png)

**Comment by developer-irfan** [comment]
@LeftAutomated assign me this task. i will add twitter logo in the footer.

**Comment by LeftAutomated** [comment]
@developer-irfan Another developer has taken on this task, sorry

**Comment by Suman373** [comment]
Is this still open?
