### ISSUE TITLE
Update Fall 2023 Officers

### ISSUE THREAD

**Issue by bnleft** [CougarCS/CougarCS-Client#552]
# Executive Board
## President
- Mihir Sahu
linkedin: https://www.linkedin.com/in/the-mihir-sahu/
email: president@cougarcs.com

## Vice President
- Johnny Le
linkedin: https://www.linkedin.com/in/le-johnny/
email: vice.president@cougarcs.com

## Executive Director - Finances
- Wahab Javed
linkedin: https://www.linkedin.com/in/wahab-javed/
email: treasurer@cougarcs.com

## Executive Director - Administration
- Michelle Nguyen
linkedin: https://www.linkedin.com/in/mnguyener2003/
email: administration@cougarcs.com

## Executive Director - CodeRED
- Benjamin Key
linkedin: https://www.linkedin.com/in/-ben-key-/
email: ben@cougarcs.com

# Director Board
## Marketing Director
- Jorell Padilla
linkedin: https://www.linkedin.com/in/jorell-padilla/
email: marketing@cougarcs.com

## Designers
- Saalihah Latiff
linkedin: https://www.linkedin.com/in/saalihah-latiff/
email: designer@cougarcs.com

- Adrian Armenta
linkedin: https://www.linkedin.com/in/adrian-armenta-92029b28b/
email: designer@cougarcs.com

## Historians 
- Hitarth Thanki
linkedin: https://www.linkedin.com/in/hitarth-thanki/
email: historian@cougarcs.com

- Sneha Jacob
linkedin: https://www.linkedin.com/in/sneha-jacob1/
email: historian@cougarcs.com

## Workshops Director
- Grace Rabano
linkedin: https://www.linkedin.com/in/grace-rabano/
email: workshops@cougarcs.com

## Corporate Relations
- Maximillian Chalitsios
linkedin: https://www.linkedin.com/in/maximillianchalitsios/
email: corporate.relations@cougarcs.com

## Socials Director
- John Cox
linkedin: https://www.linkedin.com/in/johncoxdev/
email: socials@cougarcs.com

## Operations Director
- Vaishnavi Rao
linkedin: https://www.linkedin.com/in/vaishnavi-rao-r23/
email: operations@cougarcs.com

## Operations Team Member
- Alton Phan
linkedin: https://www.linkedin.com/in/altonphan/
email: operations@cougarcs.com

- Jennifer Figueroa
linkedin: https://www.linkedin.com/in/jennifer-figueroa-maria/
email: operations@cougarcs.com

## Tutoring Director
- Tariq Achor Zyad
linkedin: https://www.linkedin.com/in/tachorzy/
email: tutoring@cougarcs.com

## Web Master 
- Bryant Le
linkedin: https://www.linkedin.com/in/bnle/
email: webmaster@cougarcs.com

## Information Security Director
- Nathan Hunt
linkedin: https://www.linkedin.com/in/nathan-hunt-bt08/
email: infosec@cougarcs.com

# Notes
- Must request for assets
- Must request for emails
- Must request for linkedin

**Comment by bnleft** [comment]
Use this photos https://drive.google.com/drive/folders/1plkECNO1LzuB8rd7yxaRpMOciBOkxo9e?usp=sharing 

- make sure to convert to .webp

**Comment by ChristopherOosthuizen** [comment]
Updated!
