### ISSUE TITLE
Update branding

### ISSUE THREAD

**Issue by bnleft** [CougarCS/CougarCS-Client#553]
# Notes
- Must request for assets

**Comment by bnleft** [comment]
Logo and background to be replaced with https://drive.google.com/drive/folders/15sIpYV1JVrQRxvnLp3_Aika_oo2x-0Jn?usp=sharing

**Comment by ChristopherOosthuizen** [comment]
Changed the main background and logo not sure if head.svg is required anywhere

**Comment by bnleft** [comment]
let's use the head as a favicon
