### ISSUE TITLE
Revised Info sec page

### ISSUE THREAD

**Issue by Brodypen** [CougarCS/CougarCS-Client#581]
Fix typos here
<img width="1102" alt="image" src="https://github.com/CougarCS/CougarCS-Client/assets/45112852/4a6b3723-9ffb-4bc2-a347-359f024a57aa">

<img width="426" alt="image" src="https://github.com/CougarCS/CougarCS-Client/assets/45112852/3b9b1ba3-4a0b-4b39-8e6d-493ac3608204">
Fix button link here
<img width="314" alt="image" src="https://github.com/CougarCS/CougarCS-Client/assets/45112852/81c04b10-8807-48fa-b2b9-b32102f9367d">

mailto:infosec@cougarcs.com?subject=CougarCS Hacker Application

**Comment by RANJEETJ06** [comment]
on click the button what you want

**Comment by fygure** [comment]
still open? pr #582
